[pytest]
testpaths =
    tests/sidecar
addopts = -q
pythonpath =
    .
    frontend/src/main/python
asyncio_mode = auto
filterwarnings =
    ignore:.*open_text is deprecated.*:DeprecationWarning
    ignore:.*joblib will operate in serial mode.*:UserWarning
    ignore:.*CUDA initialization.*:UserWarning
    ignore:There is no current event loop:DeprecationWarning
