"""WindieOS browser automation package."""

from tools.browser.chrome_detection import (
    ChromeExecutable,
    find_all_chrome_executables,
    find_chrome_executable,
)
from tools.browser.chrome_launcher import (
    ChromeLaunchTimeoutError,
    ChromeLauncher,
    ChromeLauncherError,
    ChromeNotFoundError,
    DEFAULT_CDP_URL,
    ensure_chrome_with_cdp,
    is_cdp_available,
    launch_chrome_with_cdp,
)
from tools.browser.schemas import (
    BrowserClickArgs,
    BrowserCloseArgs,
    BrowserCloseTabArgs,
    BrowserConnectArgs,
    BrowserControlArgs,
    BrowserDoneArgs,
    BrowserDropdownOptionsArgs,
    BrowserEvaluateArgs,
    BrowserExtractArgs,
    BrowserFindElementsArgs,
    BrowserFindTextArgs,
    BrowserGetTabsArgs,
    BrowserGoBackArgs,
    BrowserInputArgs,
    BrowserNavigateArgs,
    BrowserProfilesArgs,
    BrowserReadFileArgs,
    BrowserReadLongContentArgs,
    BrowserReplaceFileArgs,
    BrowserScreenshotArgs,
    BrowserScrollArgs,
    BrowserSearchArgs,
    BrowserSearchPageArgs,
    BrowserSelectDropdownArgs,
    BrowserSendKeysArgs,
    BrowserSnapshotArgs,
    BrowserStatusArgs,
    BrowserSwitchArgs,
    BrowserUploadFileArgs,
    BrowserWaitArgs,
    BrowserWriteFileArgs,
)

try:
    from tools.browser.controller import BrowserController, get_browser_controller
    from tools.browser.browser_tool import execute_browser
except ImportError:
    BrowserController = None  # type: ignore
    get_browser_controller = None  # type: ignore
    execute_browser = None  # type: ignore

__all__ = [
    "ChromeExecutable",
    "find_chrome_executable",
    "find_all_chrome_executables",
    "ChromeLauncher",
    "ensure_chrome_with_cdp",
    "launch_chrome_with_cdp",
    "is_cdp_available",
    "ChromeLauncherError",
    "ChromeNotFoundError",
    "ChromeLaunchTimeoutError",
    "DEFAULT_CDP_URL",
    "BrowserConnectArgs",
    "BrowserControlArgs",
    "BrowserNavigateArgs",
    "BrowserSnapshotArgs",
    "BrowserExtractArgs",
    "BrowserClickArgs",
    "BrowserInputArgs",
    "BrowserSendKeysArgs",
    "BrowserScrollArgs",
    "BrowserScreenshotArgs",
    "BrowserWaitArgs",
    "BrowserGetTabsArgs",
    "BrowserSwitchArgs",
    "BrowserEvaluateArgs",
    "BrowserDoneArgs",
    "BrowserSearchArgs",
    "BrowserGoBackArgs",
    "BrowserSearchPageArgs",
    "BrowserFindElementsArgs",
    "BrowserFindTextArgs",
    "BrowserCloseTabArgs",
    "BrowserDropdownOptionsArgs",
    "BrowserSelectDropdownArgs",
    "BrowserUploadFileArgs",
    "BrowserWriteFileArgs",
    "BrowserReplaceFileArgs",
    "BrowserReadFileArgs",
    "BrowserReadLongContentArgs",
    "BrowserCloseArgs",
    "BrowserProfilesArgs",
    "BrowserStatusArgs",
    "BrowserController",
    "get_browser_controller",
    "execute_browser",
]
