"""Canonical browser action contract re-exported from the shared browser contract."""

from __future__ import annotations

from windie_shared.browser_contract import (
    BROWSER_ACTION_CONTRACTS,
    BROWSER_ACTION_CONTRACTS_BY_NAME,
    BROWSER_ACTIONS_REQUIRING_CONNECTION,
    BROWSER_CANONICAL_ACTIONS,
    BROWSER_MODEL_VISIBLE_ACTIONS,
    BROWSER_RUNTIME_ACTIONS,
)

BROWSER_ALL_ACTIONS = frozenset(BROWSER_CANONICAL_ACTIONS)

__all__ = [
    "BROWSER_ACTION_CONTRACTS",
    "BROWSER_ACTION_CONTRACTS_BY_NAME",
    "BROWSER_ACTIONS_REQUIRING_CONNECTION",
    "BROWSER_ALL_ACTIONS",
    "BROWSER_CANONICAL_ACTIONS",
    "BROWSER_MODEL_VISIBLE_ACTIONS",
    "BROWSER_RUNTIME_ACTIONS",
]
