/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Incoming = PingMessage | QueryMessage | LoadSettingsMessage | ListModelsMessage | UpdateSettingsMessage;
export type Id = string;
export type Type = "ping";
export type UserId = string;
export type Id1 = string;
export type Type1 = "query";
export type Text = string;
export type UserId1 = string;
export type Id2 = string;
export type Type2 = "load-settings";
export type UserId2 = string;
export type Id3 = string;
export type Type3 = "list-models";
export type UserId3 = string;
export type Id4 = string;
export type Type4 = "update-settings";
export type UserId4 = string;
export type Id5 = string;
export type Type5 = "error";
export type Message = string;
export type Content = string | null;
export type UserId5 = string;
export type Id6 = string;
export type Type6 = "streaming-response";
export type UserId6 = string;
export type Id7 = string;
export type Type7 = "streaming-complete";
export type UserId7 = string;
export type Id8 = string;
export type Type8 = "llm-thought";
export type UserId8 = string;
export type Id9 = string;
export type Type9 = "tool-call";
export type ToolName = string;
export type UserId9 = string;
export type Id10 = string;
export type Type10 = "tool-output";
export type ToolName1 = string;
export type Success = boolean;
export type ExecutionTime = number | null;
export type Output = string;
export type Error = string | null;
export type Screenshot = string | null;
export type UserId10 = string;

export interface ClientSchema {
  incoming: Incoming;
  error: ErrorResponse;
  streaming: StreamingResponse;
  complete: StreamingComplete;
  thought: LlmThought;
  tool_call: ToolCallMessage;
  tool_output: ToolOutputMessage;
  [k: string]: unknown;
}
export interface PingMessage {
  id: Id;
  type: Type;
  payload?: Payload;
  user_id?: UserId;
  [k: string]: unknown;
}
export interface Payload {
  [k: string]: unknown;
}
export interface QueryMessage {
  id: Id1;
  type: Type1;
  payload: QueryPayload;
  user_id?: UserId1;
  [k: string]: unknown;
}
export interface QueryPayload {
  text: Text;
  screenshot_ref?: string | null;
  screenshot?: string | null;
  [k: string]: unknown;
}
export interface LoadSettingsMessage {
  id: Id2;
  type: Type2;
  payload?: Payload1;
  user_id?: UserId2;
  [k: string]: unknown;
}
export interface Payload1 {
  [k: string]: unknown;
}
export interface ListModelsMessage {
  id: Id3;
  type: Type3;
  payload?: Payload2;
  user_id?: UserId3;
  [k: string]: unknown;
}
export interface Payload2 {
  [k: string]: unknown;
}
export interface UpdateSettingsMessage {
  id: Id4;
  type: Type4;
  payload: Payload3;
  user_id?: UserId4;
  [k: string]: unknown;
}
export interface Payload3 {
  [k: string]: unknown;
}
export interface ErrorResponse {
  id: Id5;
  type: Type5;
  payload: ErrorPayload;
  user_id?: UserId5;
  [k: string]: unknown;
}
export interface ErrorPayload {
  message: Message;
  content?: Content;
  [k: string]: unknown;
}
export interface StreamingResponse {
  id: Id6;
  type: Type6;
  payload: Payload4;
  user_id?: UserId6;
  [k: string]: unknown;
}
export interface Payload4 {
  [k: string]: string;
}
export interface StreamingComplete {
  id: Id7;
  type: Type7;
  payload?: Payload5;
  user_id?: UserId7;
  [k: string]: unknown;
}
export interface Payload5 {
  [k: string]: unknown;
}
export interface LlmThought {
  id: Id8;
  type: Type8;
  payload: Payload6;
  user_id?: UserId8;
  [k: string]: unknown;
}
export interface Payload6 {
  [k: string]: string;
}
export interface ToolCallMessage {
  id: Id9;
  type: Type9;
  payload: ToolCallPayload;
  user_id?: UserId9;
  [k: string]: unknown;
}
export interface ToolCallPayload {
  tool_name: ToolName;
  parameters: Parameters;
  [k: string]: unknown;
}
export interface Parameters {
  [k: string]: unknown;
}
export interface ToolOutputMessage {
  id: Id10;
  type: Type10;
  payload: ToolOutputPayload;
  user_id?: UserId10;
  [k: string]: unknown;
}
export interface ToolOutputPayload {
  tool_name: ToolName1;
  success: Success;
  execution_time: ExecutionTime;
  output: Output;
  error: Error;
  screenshot?: Screenshot;
  [k: string]: unknown;
}
